name: Publish

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to publish (example: v1.2.3)"
        required: false
        type: string
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Setup tools with mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1

      - name: Publish to JSR
        run: deno publish
